[tool.poetry]
name = "boss-py-agent"
version = "0.2.0"
description = "BOSS Python Agent - A self-evolving implementation generator powered by Claude API"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "boss_py_agent"}]

[tool.poetry.dependencies]
python = "^3.9"
anthropic = "^0.49.0"
python-dotenv = "^1.0.0"
psutil = "^5.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
pylint = "^2.17.0"
black = "^23.3.0"
mypy = "^1.3.0"

[tool.poetry.group.viz.dependencies]
matplotlib = "^3.7.1"
rich = "^13.3.5"
jsonschema = "^4.17.3"

[tool.poetry.scripts]
boss = "boss_py_agent:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ["py39"]
include = '\.pyi?$'

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "--cov=boss_py_agent --cov-report=term-missing"
